1. Importe el paquete numpy con el nombre np

In [2]:
import numpy as np      # Importación del paquete numpy

2. Imprima la versión numpy y la configuración 

In [5]:
print(np.__version__)             # Versión
np.show_config()                  # Configuración

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Francisco/anaconda4\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Francisco/anaconda4\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Francisco/anaconda4\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\w

3. Cree un vector nulo de tamaño 10

In [6]:
x = np.zeros(10)        # Vector x que almacena 10 valores nulos
print(x)                # Muestro por pantalla

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. Cómo encontrar el tamaño de la memoria de cualquier arreglo

In [12]:
z = np.zeros((10,10))       # Variable z que almacena una matriz 10x10
print("El tamaño de la memoria es de",z.itemsize,"bits")  # Muestro el resultado


El tamaño de la memoria es de 8 bits


5. ¿Cómo obtener la documentación de la función numpy add desde la línea de comandos?

In [14]:
import numpy;numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

6. Cree un vector nulo de tamaño 10 pero el quinto valor que es 1 

In [16]:
f = np.zeros(10)     # Variable f que almacena 10 vectores nulos
f[4] = 1             # Que en la posicion 4 ponga un 1
print(f)             # Muestro el resultado

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Cree un vector con valores entre 10 y 49 

In [17]:
r = np.arange(10,50)     # Variable r que almacena un vector del número 10 al 49
print(r)                 # Muestro el resultado

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Invierta un vector (el primer elemento se convierte en el último)

In [21]:
e = np.arange(1,11)       # Variable e que almacena un vector del número 1 al 10
print(e[::-1])            # Muestro el resultado del vector invertido

[10  9  8  7  6  5  4  3  2  1]


9. Cree una matriz de 3x3 con valores de 0 a 8 

In [23]:
n = np.arange(9)          # Variable n que almacena un vector de 9 números

n.shape = (3,3)           # Creación de una matriz 3x3 con el vector de 9 números
print(n)                  # Muestro el resultado





[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Encuentre índices de elementos distintos de cero de [1,2,0,0,4,0]

In [25]:
indices_sin_ceros = []         # Variable para almacenar los indices sin ceros
lista = [1,2,0,0,4,0]          # Lista
for i in range(len(lista)):    # Bucles para recorrer los indices de la lista
    if lista[i] != 0:
        indices_sin_ceros.append(i)
        
print(indices_sin_ceros)       # Muestro los indices que no contienen cero

[0, 1, 4]


11. Cree una matriz de identidad de 3x3

In [26]:
h = np.eye(3)         # Variable que almacena una matriz identidad 3x3
print(h)              # Muestro el resultado por pantalla

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Cree una matriz de 3x3x3 con valores aleatorios